import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useFetch } from "@/api/hooks/useFetch";
import { _Urls } from "@/api/_Urls";
import { useCategories } from "@/context/auth/CategoriesContext";
import { Card } from "@/components";
import styled from "styled-components";
import Link from "next/link";
import GridContainer from "@/components/GridContainer/GridContainer";



export default function Home() {
  const { categories } = useCategories();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GridContainer>
        {Object.keys(categories).map((item) => {
          return (
            <Link href={`./${item}`}>
              <Card>{item}</Card>
            </Link>
          );
        })}
      </GridContainer>
    </>
  );
}
