const root = "https://pokeapi.co/api/v2";

export const _Urls = {
  root: root,
//   ability: "/v2/ability/",
//   berry: "/v2/berry/",
//   "berry-firmness": "/v2/berry-firmness/",
//   "berry-flavor": "/v2/berry-flavor/",
//   characteristic: "/v2/characteristic/",
//   "contest-effect": "/v2/contest-effect/",
//   "contest-type": "/v2/contest-type/",
//   "egg-group": "/v2/egg-group/",
//   "encounter-condition": "/v2/encounter-condition/",
//   "encounter-condition-value": "/v2/encounter-condition-value/",
//   "encounter-method": "/v2/encounter-method/",
//   "evolution-chain": "/v2/evolution-chain/",
//   "evolution-trigger": "/v2/evolution-trigger/",
//   gender: "/v2/gender/",
//   generation: "/v2/generation/",
//   "growth-rate": "/v2/growth-rate/",
//   item: "/v2/item/",
//   "item-attribute": "/v2/item-attribute/",
//   "item-category": "/v2/item-category/",
//   "item-fling-effect": "/v2/item-fling-effect/",
//   "item-pocket": "/v2/item-pocket/",
//   language: "/v2/language/",
//   location: "/v2/location/",
//   "location-area": "/v2/location-area/",
//   machine: "/v2/machine/",
//   move: "/v2/move/",
//   "move-ailment": "/v2/move-ailment/",
//   "move-battle-style": "/v2/move-battle-style/",
//   "move-category": "/v2/move-category/",
//   "move-damage-class": "/v2/move-damage-class/",
//   "move-learn-method": "/v2/move-learn-method/",
//   "move-target": "/v2/move-target/",
//   nature: "/v2/nature/",
//   "pal-park-area": "/v2/pal-park-area/",
//   "pokeathlon-stat": "/v2/pokeathlon-stat/",
//   pokedex: "/v2/pokedex/",
//   pokemon: "/v2/pokemon/",
//   "pokemon-color": "/v2/pokemon-color/",
//   "pokemon-form": "/v2/pokemon-form/",
//   "pokemon-habitat": "/v2/pokemon-habitat/",
//   "pokemon-shape": "/v2/pokemon-shape/",
//   "pokemon-species": "/v2/pokemon-species/",
//   region: "/v2/region/",
//   stat: "/v2/stat/",
//   "super-contest-effect": "/v2/super-contest-effect/",
//   type: "/v2/type/",
//   version: "/v2/version/",
//   "version-group": "/v2/version-group/",
};
